### PR TITLE
feature: update ngrx version to 13.0.1

### PR DESCRIPTION
**Pull request by mehrad-rafigh**
When running schematics and adding the ngrx flag, the following error occurs

```
npx ng g @angular-architects/ddd:feature damage-assessment --domain olb --entity damage --ngrx --type publishable --app example --importPath @ewp/olb/damage-assessment                    
⠸ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: enterprise-web-platform@0.0.0
npm ERR! Found: @angular/core@13.0.2
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^13.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"^10.0.0" from @ngrx/effects@10.1.2
npm ERR! node_modules/@ngrx/effects
npm ERR!   @ngrx/effects@"10.1.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/mehrad/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mehrad/.npm/_logs/2021-11-30T13_52_12_144Z-debug.log
✖ Package install failed, see above.
UnsuccessfulWorkflowExecution [Error]: Workflow did not execute successfully.
    at ChildProcess.<anonymous> (/home/mehrad/dev/work/enterprise-web-platform/node_modules/@angular-devkit/schematics/tasks/package-manager/executor.js:134:31)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
The generator workflow failed. See above.
```

### CODE REVIEW

**Comment by mehrad-rafigh** [comment]
@manfredsteyer @benpsnyder @peterbsmyth can we get this reviewed and merged please? Its blocking my team and we really like to use this plugin.
Cheers

**Comment by benpsnyder** [comment]
@mehrad-rafigh first we should merge [Upgrade to Yarn v3, Nx 13.1.4, and move to @nrwl/nx-plugin proper structure #91](https://github.com/angular-architects/nx-ddd-plugin/pull/91)

**Comment by benpsnyder** [comment]
> @manfredsteyer @benpsnyder @peterbsmyth can we get this reviewed and merged please? Its blocking my team and we really like to use this plugin. Cheers

In the meantime, you can have your team do the following:
- `<ProjectsDir>/<yourProject>`
- `<ProjectsDir>/nx-ddd-plugin`

Have them switch branches on `<ProjectsDir>/nx-ddd-plugin` to include your changes
- run `yarn build`

On `<ProjectsDir>/<yourProject>/package.json` update the `@angular-architects/ddd` dependency to be:
````
"@angular-architects/ddd": "file:../nx-ddd-plugin/dist/libs/ddd", 
````
Then when you run `yarn install` from `<ProjectsDir>/<yourProject>/` it will use the locally built version of @angular-architects/ddd which has your customizations. You don't need to wait for @manfredsteyer to publish to NPM

**Comment by mehrad-rafigh** [comment]
@benpsnyder Thank you for the guide. Much appreciated :)

**Pull request closed without merging**
